# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MatchBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BrightFutures'


  # Pods for MatchBook

  target 'MatchBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MatchBookUITests' do
    # Pods for testing
  end

end
